services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql_sistema
    environment:
      MYSQL_ROOT_PASSWORD: Root.123.4
      MYSQL_DATABASE: horas_servicio
    ports:
      - "3307:3306"


  backend-api:
    build: ../back/backend-api
    container_name: backend-api
    ports:
      - 8080:8080
    depends_on:
      - mysql

  frontend-mvc:
    build: ../front/frontend-mvc
    container_name: fronend-mvc
    ports:
      - 8081:8081
    depends_on:
      - backend-api