spring.application.name=backend-api

spring.datasource.url=jdbc:mysql://localhost:3306/horas_servicio_lab_macrodatos
spring.datasource.username=root
spring.datasource.password=Root.123.4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
